### ISSUE TITLE
Add support for Godot 4.0

### ISSUE THREAD

**Issue by tscrypter** [jitspoe/godot-console#1]
Now that [Godot 4.0 has entered beta](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) and this extension is awesome, it would be great if it works on 4.0 as well.

**Comment by tscrypter** [comment]
I've got a fork and have started making some progress towards this, but I wanted to create an issue to track my branch against.

**Comment by jitspoe** [comment]
Godot 4 is now properly supported!  3.x support moved to a separate branch.
