### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by herrobriam** [jitspoe/godot-console#14]
The other project you provided for C# support hasn't received commits in a year, thus is broken. Your project has problems with C#, such as being unable to add commands. It would be good if you could provide support for C# in your project.

**Comment by MolikoDeveloper** [comment]
hi, i made the C# version a year ago like you said, let me get some time to update it for the new version of Godot.

for now, im working in other project and the game hobbie was taken away 😥

**Comment by herrobriam** [comment]
> hi, i made the C# version a year ago like you said, let me get some time to update it for the new version of Godot.
> 
> 
> 
> for now, im working in other project and the game hobbie was taken away 😥 

i got your version workint by simply copy and pasting the code from the addons folder into my own scripts folder, removing anything related to it being a plugin and it works flawlessly. you dont need to do much work other than updating the plugin.cfg

**Comment by jitspoe** [comment]
I'm going to close this as I'm not actually supporting C#.
