### ISSUE TITLE
Console is null when plugin is calling is_visible

### ISSUE THREAD

**Issue by Levrault** [jitspoe/godot-console#17]
Hi,

I work both on linux and windows for my game, I use Godot 4.3 stable. Everything worked as expected but when switching to my windows PC, I got the following error

![image](https://github.com/user-attachments/assets/5714cb42-7faf-46e6-ae85-984d45461fa2)

I re-install the plugin and still the same result. I added a temporary quickfix 

```
func is_visible():
	if not control:
		return false
	return control.visible
```

Do you have any clues why this is happening ?

Thanks

**Comment by jitspoe** [comment]
If you had an older version of the console and updated it, it might be because I changed the filename and godot cached it.  There are some cache .cfg files in the .godot directory you can try deleting (back up first) and see if that helps.

Oh, wait, actually, I see the problem.  You're calling something on the console from _enter_tree, but that stuff gets initialized in ready.  You can probably just delete the "@onready" before the control is initialized, so it's just "var control := Control.new()".  I guess I should make a patch to initialize that stuff pre-ready in case people do some stuff with it prior to ready being called.

What do you call in your refresh_step() function?

**Comment by Levrault** [comment]
Hi thanks for the reply,

For refresh_step, it's coming from proton scatter addons. I disable the plugin but still have the issue.

I deleted my .godot folder to refresh the case (good thing, I needed it for another issue) but the error was still there. Here how I implemeted the console.

I use a scene called game.tscn where I create all the magic. My terminal node is what using the console plugin.
![image](https://github.com/user-attachments/assets/bd999b91-0be1-442d-b25d-b9ad6e74531f)

Here the script where I use the plugin, I initilize everything in the _ready function.

```
@icon("res://editor/icons/terminal.svg")
extends Node


func _ready() -> void:
	Console.pause_enabled = true
	Console.add_command("spawn", spawn, ["props"])
	Console.add_command("god_mode", god_mode, ["enabled"], 1, "Pretty self explanatory")
	Console.add_command("give", give, ["item_name"], 1, "Spawns the specified item in your inventory.")
	Console.add_command("spawn", spawn, ["item_name"], 1, "Spawns the specified item or creature in front of you.")
	Console.add_command("no_clip", no_clip, ["enabled"], 1, "Pass through walls (except bullets.)")
	Console.add_command("kill", kill, ["entity_name"], 1, "Kill the specified entity")


func give(item_name: String) -> void:
	var item: Dictionary = _get_item_by_name(item_name)
	if not item.has("entity_data_resource"):
		Console.print_line("%s has not been gived to the player, entity_data_resource not found" % item_name)
		return
	Console.print_line("%s has been gived to the player" % item_name)
	Events.console_item_gived.emit(item.entity_data_resource)


func spawn(item_name: String) -> void:
	var item: Dictionary = _get_item_by_name(item_name)
	if not item.has("packed_scene"):
		Console.print_line("%s has not been spawned, packed_scene not found" % item_name)
		return
	Console.print_line("%s has been spawned" % item_name)
	Events.console_item_spawned.emit(item.packed_scene)


func god_mode(enabled: bool) -> void:
	Console.print_line("god_mode need to be added")


func no_clip(enabled: bool) -> void:
	Console.print_line("no_clip need to be added")


func kill(entity_name: String) -> void:
	Console.print_line("kill need to be added")


func _get_item_by_name(item_name: String) -> Dictionary:
	match item_name:
		"ammo_box_revolver":
			return {
				packed_scene = load("res://weapons/webley_revolver/sm_webley_ammo_box.tscn"),
				entity_data_resource = load("res://weapons/webley_revolver/resources/er_revolver_ammo_box.tres")
			}
		"fakeboy":
			return {
				packed_scene = load("res://props/fakeboy/sm_fake_boy.tscn"),
				entity_data_resource = load("res://props/fakeboy/er_fakeboy.tres")
			}
		"godot_plushie":
			return {
				packed_scene = load("res://props/godot_plushie/sm_godot_plushie.tscn"),
				entity_data_resource = load("res://props/godot_plushie/er_godot_plushie.tres")
			}
		"revolver":
			return {
				packed_scene = load("res://weapons/webley_revolver/sm_webley_revolver.tscn"),
				entity_data_resource = load("res://weapons/webley_revolver/resources/er_sk_revolver.tres")
			}
		"whisky":
			return {
				packed_scene = load("res://props/whisky_bottle_01/sm_whisky_bottle_01.tscn"),
				entity_data_resource = load("res://props/whisky_bottle_01/er_whisky_bottle_01.tres")
			}
		_:
			return {}

```

**Comment by jitspoe** [comment]
Interesting.  What's the callstack on the error without the scatter addon?  Also, did you try removing the onready before "var control := Control.new()" in the console addon?

**Comment by Levrault** [comment]
Hi, sorry I forgot to do that. Yes, it actually fix the issue!

**Comment by jitspoe** [comment]
Ok, officially fixed here: https://github.com/jitspoe/godot-console/commit/bf2fab964fcd8244892b49831ca825c974e05549
