### ISSUE TITLE
I made a tiny version in c#

### ISSUE THREAD

**Issue by MolikoDeveloper** [jitspoe/godot-console#6]
# C# version is on Github Repositoy:

[Repository here](https://github.com/MolikoDeveloper/Csharp-Console-Godot)

is almost made exactly what you console do, inclomplete, but there is it.

example:
```c#
public partial class Example : Node
{
	public override void _Ready()
	{
		GetNode<CommandConsole>("/root/CommandConsole").AddCommand("test", test);
    	}

    	void test(string text)
    	{
        	GD.Print(text);
    	}
}
```

in game run with:
> `test` "testing the example" => set `testing the example` as param value
> `test` testing the example => set `testing` `the` `example` as params values
> `test` "testing the" example => set `testing the` `example` as params

all with a maximum of 16 params.

**Comment by jitspoe** [comment]
Awesome!

**Comment by MolikoDeveloper** [comment]
thanks.
