### ISSUE TITLE
Toggling console prevent AnimationPlayer from playing

### ISSUE THREAD

**Issue by xXAnoHitoXx** [jitspoe/godot-console#9]
when Console.toggle is called,
AnimationPlayer.play() do play the animation, i.e. AnimationPlayer.isPlaying() returns true,

however with the console toggled the TextureRect does not recieve updates from AnimationPlayer

https://github.com/jitspoe/godot-console/assets/23743678/3870bd7d-8d70-4b35-b6bf-bcf3ddc61a11

**Comment by xXAnoHitoXx** [comment]
turns out problem is that by default the console pauses the scenetree.

it'd be great to have this information displayed somewhere / have a clearer way to enable/disable this behaviour

**Comment by jitspoe** [comment]
Yeah, I was trying to emulate the behavior of Quake and other games that have the console, which pause the game to allow you to do things and not have to worry about time constraints.  If you want, you can connect to the console_opened signal and manually unpause the game, or set your scene to process while paused.  This isn't documented well, though.  If you suggestions for where to put that information, let me know!

**Comment by xXAnoHitoXx** [comment]
I'd say either in the read me page, or a comment on top of toggle console method. It'd be nice to have more detailed documentation on how the addon functions. Otherwise a comment on the method to alert user about the side effect of pausing would help.

The easiest way I think is to take that bit out and let the people who do want to pause add it in intentionally.
